apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
  - name: todoapp
    image: godfri/todoapp:3.0.0
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /api/healthz
        port: 8000
    readinessProbe:
      httpGet:
        path: /api/ready
